### ISSUE TITLE
Hide single cross-links

### ISSUE THREAD

**Issue by fjoreilly** [Rappsilber-Laboratory/xiUI#223]
I would like to be able to visualise only the most confident protein-protein interactions in my networks by filtering based on the number of residue or peptide pairs between two proteins.

thanks.

**Comment by colin-combe** [comment]
ok, do-able. 

Could we make it based solely on the count of linked residue pairs? Its easier / fewer additional controls in interface and the issue is called 'hide single cross-links' so that seems to be the important thing?

cheers,
c

**Comment by fjoreilly** [comment]
Exactly as you said.  Thanks

**Comment by colin-combe** [comment]
OK, you should have this now - its called "Residue Pairs per PPI", its at the bottom right
